/*

 GRUNDTILES_44-29.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 29 to 44

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __grundtiles_44_29_h_INCLUDE
#define __grundtiles_44_29_h_INCLUDE

/* Bank of tiles. */
#define grundtilesBank 0
/* Start of tile array. */
extern const unsigned char grundtiles[];

#endif

/* End of GRUNDTILES_44-29.H */
