/*

 TILES_79-45.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 45 to 79

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tiles_79_45_h_INCLUDE
#define __tiles_79_45_h_INCLUDE

/* Bank of tiles. */
#define tilesBank 0
/* Start of tile array. */
extern const unsigned char tiles[];

#endif

/* End of TILES_79-45.H */
